wandb_version: 1

input_size:
  desc: null
  value: 224
_wandb:
  desc: null
  value:
    python_version: 3.8.15
    cli_version: 0.15.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1694831190.32474
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      2:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      3:
      - 2
      - 3
      - 23
      - 37
      4: 3.8.15
      5: 0.15.10
      8:
      - 2
      - 5
